//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dialog.DialogStrings", typeof(DialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach kritischen Texten.
        /// </summary>
        public static string chkCriticalText {
            get {
                return ResourceManager.GetString("chkCriticalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach kritischen Texten.
        /// </summary>
        public static string chkCriticalTextReport {
            get {
                return ResourceManager.GetString("chkCriticalTextReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach kurzen Verwendungszwecken.
        /// </summary>
        public static string chkShortText {
            get {
                return ResourceManager.GetString("chkShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach kurzen Verwendungszwecken.
        /// </summary>
        public static string chkShortTextReport {
            get {
                return ResourceManager.GetString("chkShortTextReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche kritische Buchungstexte als ganzes Wort.
        /// </summary>
        public static string chkWordSearch {
            get {
                return ResourceManager.GetString("chkWordSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche kritische Buchungstexte als ganzes Wort.
        /// </summary>
        public static string chkWordSearchReport {
            get {
                return ResourceManager.GetString("chkWordSearchReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umsätze mit kritischen Verwendungszwecken.
        /// </summary>
        public static string frmTitle {
            get {
                return ResourceManager.GetString("frmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf Feldname &quot;KONTO_NR&quot;:.
        /// </summary>
        public static string ftlCaption {
            get {
                return ResourceManager.GetString("ftlCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf Feldname &quot;RAHMENNR_2STELLIG&quot;:.
        /// </summary>
        public static string ftlCaption2 {
            get {
                return ResourceManager.GetString("ftlCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von/Einzelwert:.
        /// </summary>
        public static string ftlCaptionFrom {
            get {
                return ResourceManager.GetString("ftlCaptionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von/Einzelwert:.
        /// </summary>
        public static string ftlCaptionFrom2 {
            get {
                return ResourceManager.GetString("ftlCaptionFrom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis:.
        /// </summary>
        public static string ftlCaptionTo {
            get {
                return ResourceManager.GetString("ftlCaptionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis:.
        /// </summary>
        public static string ftlCaptionTo2 {
            get {
                return ResourceManager.GetString("ftlCaptionTo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf Kontonummern.
        /// </summary>
        public static string ftlReportName {
            get {
                return ResourceManager.GetString("ftlReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf Rahmennummern.
        /// </summary>
        public static string ftlReportName2 {
            get {
                return ResourceManager.GetString("ftlReportName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf das Buchungsdatum.
        /// </summary>
        public static string labCaption {
            get {
                return ResourceManager.GetString("labCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf das Buchungsdatum.
        /// </summary>
        public static string labCaptionReport {
            get {
                return ResourceManager.GetString("labCaptionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchungsdatum von:.
        /// </summary>
        public static string labDateFrom {
            get {
                return ResourceManager.GetString("labDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis:.
        /// </summary>
        public static string labDateTo {
            get {
                return ResourceManager.GetString("labDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestbetrag:.
        /// </summary>
        public static string labMinVal {
            get {
                return ResourceManager.GetString("labMinVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse der Textlänge:.
        /// </summary>
        public static string labOptions {
            get {
                return ResourceManager.GetString("labOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit einer Zeichenlänge von bis zu:.
        /// </summary>
        public static string labShortHead {
            get {
                return ResourceManager.GetString("labShortHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit einer Zeichenlänge von bis zu:.
        /// </summary>
        public static string labShortText {
            get {
                return ResourceManager.GetString("labShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritische Texte.
        /// </summary>
        public static string labTabPage1 {
            get {
                return ResourceManager.GetString("labTabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textlänge.
        /// </summary>
        public static string labTabPage2 {
            get {
                return ResourceManager.GetString("labTabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontonummernauswahl.
        /// </summary>
        public static string labTabPage3 {
            get {
                return ResourceManager.GetString("labTabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahmennummer.
        /// </summary>
        public static string labTabPage4 {
            get {
                return ResourceManager.GetString("labTabPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilanzposition.
        /// </summary>
        public static string labTabPage5 {
            get {
                return ResourceManager.GetString("labTabPage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte überprüfen Sie Ihre Eingaben. Mindestens eine Analyse-Option in den Registerkarten Kritische Texte oder Textlänge muss ausgewählt werden..
        /// </summary>
        public static string msgAnalyzeValid {
            get {
                return ResourceManager.GetString("msgAnalyzeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte überprüfen Sie Ihre Eingaben. Das Von-Datum muss vor dem Bis-Datum liegen..
        /// </summary>
        public static string msgDateValid {
            get {
                return ResourceManager.GetString("msgDateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte überprüfen Sie Ihre Eingaben. Mindestens ein Wert muss der Liste der kritischen Buchungstexte hinzugefügt werden..
        /// </summary>
        public static string msgValidCritText {
            get {
                return ResourceManager.GetString("msgValidCritText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der kritischen Buchungstexte:.
        /// </summary>
        public static string slCaption {
            get {
                return ResourceManager.GetString("slCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf Feldname &quot;POSITION_SHORT&quot;:.
        /// </summary>
        public static string slCaption2 {
            get {
                return ResourceManager.GetString("slCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste der kritischen Buchungstexte.
        /// </summary>
        public static string slCaptionReport {
            get {
                return ResourceManager.GetString("slCaptionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einschränkung auf Feldname &quot;POSITION_SHORT&quot;.
        /// </summary>
        public static string slCaptionReport2 {
            get {
                return ResourceManager.GetString("slCaptionReport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchungsdatum von.
        /// </summary>
        public static string txtDateFromReportName {
            get {
                return ResourceManager.GetString("txtDateFromReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchungsdatum bis.
        /// </summary>
        public static string txtDateToReportName {
            get {
                return ResourceManager.GetString("txtDateToReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestbetrag.
        /// </summary>
        public static string txtMinValReportName {
            get {
                return ResourceManager.GetString("txtMinValReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach kurzen Verwendungszwecken mit einer Zeichenlänge von bis zu.
        /// </summary>
        public static string txtShortTextReportName {
            get {
                return ResourceManager.GetString("txtShortTextReportName", resourceCulture);
            }
        }
    }
}
