//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dialog {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dialog.DialogStrings", typeof(DialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweise ähnelt.
        /// </summary>
        internal static string btnHint {
            get {
                return ResourceManager.GetString("btnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        /// </summary>
        internal static string contextClient {
            get {
                return ResourceManager.GetString("contextClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        internal static string contextServer {
            get {
                return ResourceManager.GetString("contextServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stichprobenziehung ähnelt.
        /// </summary>
        internal static string frmTitle {
            get {
                return ResourceManager.GetString("frmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss ein Wert für die Zufallsauswahl eingegeben werden. ähnelt.
        /// </summary>
        internal static string msgRule1 {
            get {
                return ResourceManager.GetString("msgRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss ein Wert für den Cut Off obere Grenze eingegeben werden. ähnelt.
        /// </summary>
        internal static string msgRule2 {
            get {
                return ResourceManager.GetString("msgRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss ein Wert für den Cut Off untere Grenze eingegeben werden. ähnelt.
        /// </summary>
        internal static string msgRule3 {
            get {
                return ResourceManager.GetString("msgRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss ein Wert für das Feld für den Cut Off ausgewählt werden. ähnelt.
        /// </summary>
        internal static string msgRule4 {
            get {
                return ResourceManager.GetString("msgRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie eine Datei auf Ihrem lokalen Computer. ähnelt.
        /// </summary>
        internal static string MsgSelectLocalTable {
            get {
                return ResourceManager.GetString("MsgSelectLocalTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie eine Datei auf dem IDEA server. ähnelt.
        /// </summary>
        internal static string MsgSelectServerTable {
            get {
                return ResourceManager.GetString("MsgSelectServerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        internal static string smartBtnBrowseToolTip {
            get {
                return ResourceManager.GetString("smartBtnBrowseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zufallsauswahl ähnelt.
        /// </summary>
        internal static string smartCheckBox1Report {
            get {
                return ResourceManager.GetString("smartCheckBox1Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zufallsauswahl ähnelt.
        /// </summary>
        internal static string smartCheckBox1Text {
            get {
                return ResourceManager.GetString("smartCheckBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut Off obere Grenze (&gt;=) ähnelt.
        /// </summary>
        internal static string smartCheckBox2Report {
            get {
                return ResourceManager.GetString("smartCheckBox2Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut Off obere Grenze (&gt;=) ähnelt.
        /// </summary>
        internal static string smartCheckBox2Text {
            get {
                return ResourceManager.GetString("smartCheckBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut Off untere Grenze (&lt;=) ähnelt.
        /// </summary>
        internal static string smartCheckBox3Report {
            get {
                return ResourceManager.GetString("smartCheckBox3Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut Off untere Grenze (&lt;=) ähnelt.
        /// </summary>
        internal static string smartCheckBox3Text {
            get {
                return ResourceManager.GetString("smartCheckBox3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Betragsspalte ähnelt.
        /// </summary>
        internal static string smartComboBox1Label {
            get {
                return ResourceManager.GetString("smartComboBox1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Betragsspalte ähnelt.
        /// </summary>
        internal static string smartComboBox1Report {
            get {
                return ResourceManager.GetString("smartComboBox1Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung ähnelt.
        /// </summary>
        internal static string smartComboBox2Label {
            get {
                return ResourceManager.GetString("smartComboBox2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung ähnelt.
        /// </summary>
        internal static string smartComboBox2Report {
            get {
                return ResourceManager.GetString("smartComboBox2Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl der Datei für die Stichprobenziehung ähnelt.
        /// </summary>
        internal static string smartLabel12Text {
            get {
                return ResourceManager.GetString("smartLabel12Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuweisung des Feldes für den Cut Off ähnelt.
        /// </summary>
        internal static string smartLabel13Text {
            get {
                return ResourceManager.GetString("smartLabel13Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei für die Stichprobenziehung ähnelt.
        /// </summary>
        internal static string smartTextBox1Report {
            get {
                return ResourceManager.GetString("smartTextBox1Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert für Zufallsauswahl ähnelt.
        /// </summary>
        internal static string smartTextBox2Report {
            get {
                return ResourceManager.GetString("smartTextBox2Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert für Cut Off obere Grenze ähnelt.
        /// </summary>
        internal static string smartTextBox3Report {
            get {
                return ResourceManager.GetString("smartTextBox3Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert für Cut Off untere Grenze ähnelt.
        /// </summary>
        internal static string smartTextBox4Report {
            get {
                return ResourceManager.GetString("smartTextBox4Report", resourceCulture);
            }
        }
    }
}
